# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ $(uname -s) == "Darwin" ]]; then
    DOTFILES=~/projects/perso/dotfiles
else 
    DOTFILES=/mnt/data/backup/dev/projects/dotfiles
fi

export PATH=$DOTFILES/bin:$PATH
SPARK_DIR=~/opt/spark
[[ -f $SPARK_DIR ]] && export PATH=$SPARK_DIR/bin:$PATH
[[ -f ~/opt/bin ]] && export PATH=~/opt/bin:$PATH

function cl() {
    echo "$1" >> $DOTFILES/bin/yamocl.txt
}

alias cat='bat'
alias drmi='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias du="ncdu --color dark"
alias dush="\du -sh | sort -h | tail"
alias h=history
alias penguen="ssh penguen -t tmux a"
alias rr='ranger'
alias todo="vim ~/Dropbox/Documents/TODO.txt"
alias tv="vlc http://mafreebox.freebox.fr/freeboxtv/playlist.m3u"

# https://github.com/StreakyCobra/gws/issues/17
alias gws="PATH=/usr/local/opt/coreutils/libexec/gnubin:usr/local/opt/gnu-sed/libexec/gnubin:$PATH gws"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias javals='/usr/libexec/java_home -V' #osx
export JAVA_HOME="$(/usr/libexec/java_home -v '1.8')"

function j8() {
    export JAVA_HOME="$(/usr/libexec/java_home -v '1.8*')"
}
function j11() {
    export JAVA_HOME="$(/usr/libexec/java_home -v 'Zulu 11')"
}

alias coursier_update='curl -Lo ~/opt/bin/coursier https://git.io/coursier-cli'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Source in your profile to enable shell command completion for gcloud.
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# Source in your profile to add the Google Cloud SDK command line tools to your $PATH.
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc

fif() {
	rg  \
	--column \
	--line-number \
	--no-column \
	--no-heading \
	--fixed-strings \
	--ignore-case \
	--hidden \
	--follow \
	--glob '!.git/*' "$1" \
	| awk -F  ":" '/1/ {start = $2<5 ? 0 : $2 - 5; end = $2 + 5; print $1 " " $2 " " start ":" end}' \
	| fzf --preview 'bat --wrap character --color always {1} --highlight-line {2} --line-range {3}' --preview-window wrap
}
